# Linker order for every file, passed to the Metrowerks linker.

O_FILES := \
	$(BUILD_DIR)/src/emulator/xlCoreGCN.o \
	$(BUILD_DIR)/src/emulator/xlPostGCN.o \
	$(BUILD_DIR)/src/emulator/xlFileGCN.o \
	$(BUILD_DIR)/src/emulator/xlList.o \
	$(BUILD_DIR)/src/emulator/xlHeap.o \
	$(BUILD_DIR)/src/emulator/xlObject.o \
	$(BUILD_DIR)/src/emulator/simGCN.o \
	$(BUILD_DIR)/src/emulator/movie.o \
	$(BUILD_DIR)/src/emulator/THPPlayer.o \
	$(BUILD_DIR)/src/emulator/THPAudioDecode.o \
	$(BUILD_DIR)/src/emulator/THPDraw.o \
	$(BUILD_DIR)/src/emulator/THPRead.o \
	$(BUILD_DIR)/src/emulator/THPVideoDecode.o \
	$(BUILD_DIR)/src/emulator/mcardGCN.o \
	$(BUILD_DIR)/src/emulator/codeGCN.o \
	$(BUILD_DIR)/src/emulator/soundGCN.o \
	$(BUILD_DIR)/src/emulator/frame.o \
	$(BUILD_DIR)/src/emulator/system.o \
	$(BUILD_DIR)/src/emulator/cpu.o \
	$(BUILD_DIR)/src/emulator/pif.o \
	$(BUILD_DIR)/src/emulator/ram.o \
	$(BUILD_DIR)/src/emulator/rom.o \
	$(BUILD_DIR)/src/emulator/rdp.o \
	$(BUILD_DIR)/src/emulator/rdb.o \
	$(BUILD_DIR)/asm/rsp.o \
	$(BUILD_DIR)/src/emulator/mips.o \
	$(BUILD_DIR)/src/emulator/disk.o \
	$(BUILD_DIR)/src/emulator/flash.o \
	$(BUILD_DIR)/src/emulator/sram.o \
	$(BUILD_DIR)/src/emulator/audio.o \
	$(BUILD_DIR)/src/emulator/video.o \
	$(BUILD_DIR)/src/emulator/serial.o \
	$(BUILD_DIR)/src/emulator/library.o \
	$(BUILD_DIR)/src/emulator/peripheral.o \
	$(BUILD_DIR)/src/emulator/_frameGCNcc.o \
	$(BUILD_DIR)/src/emulator/_buildtev.o \
	$(BUILD_DIR)/src/dolphin/base/PPCArch.o \
	$(BUILD_DIR)/src/dolphin/os/OS.o \
	$(BUILD_DIR)/src/dolphin/os/OSAlarm.o \
	$(BUILD_DIR)/src/dolphin/os/OSAlloc.o \
	$(BUILD_DIR)/src/dolphin/os/OSArena.o \
	$(BUILD_DIR)/src/dolphin/os/OSAudioSystem.o \
	$(BUILD_DIR)/src/dolphin/os/OSCache.o \
	$(BUILD_DIR)/src/dolphin/os/OSContext.o \
	$(BUILD_DIR)/src/dolphin/os/OSError.o \
	$(BUILD_DIR)/src/dolphin/os/OSFont.o \
	$(BUILD_DIR)/src/dolphin/os/OSInterrupt.o \
	$(BUILD_DIR)/src/dolphin/os/OSLink.o \
	$(BUILD_DIR)/src/dolphin/os/OSMessage.o \
	$(BUILD_DIR)/src/dolphin/os/OSMemory.o \
	$(BUILD_DIR)/src/dolphin/os/OSMutex.o \
	$(BUILD_DIR)/src/dolphin/os/OSReboot.o \
	$(BUILD_DIR)/src/dolphin/os/OSReset.o \
	$(BUILD_DIR)/src/dolphin/os/OSResetSW.o \
	$(BUILD_DIR)/src/dolphin/os/OSRtc.o \
	$(BUILD_DIR)/src/dolphin/os/OSSync.o \
	$(BUILD_DIR)/src/dolphin/os/OSThread.o \
	$(BUILD_DIR)/src/dolphin/os/OSTime.o \
	$(BUILD_DIR)/src/dolphin/os/__start.o \
	$(BUILD_DIR)/src/dolphin/os/__ppc_eabi_init.o \
	$(BUILD_DIR)/src/dolphin/exi/EXIBios.o \
	$(BUILD_DIR)/src/dolphin/exi/EXIUart.o \
	$(BUILD_DIR)/src/dolphin/si/SIBios.o \
	$(BUILD_DIR)/src/dolphin/si/SISamplingRate.o \
	$(BUILD_DIR)/src/dolphin/vi/vi.o \
	$(BUILD_DIR)/src/dolphin/db/db.o \
	$(BUILD_DIR)/src/dolphin/mtx/mtx.o \
	$(BUILD_DIR)/src/dolphin/mtx/mtxvec.o \
	$(BUILD_DIR)/src/dolphin/mtx/mtx44.o \
	$(BUILD_DIR)/src/dolphin/gx/GXInit.o \
	$(BUILD_DIR)/src/dolphin/gx/GXFifo.o \
	$(BUILD_DIR)/src/dolphin/gx/GXAttr.o \
	$(BUILD_DIR)/src/dolphin/gx/GXMisc.o \
	$(BUILD_DIR)/src/dolphin/gx/GXGeometry.o \
	$(BUILD_DIR)/src/dolphin/gx/GXFrameBuf.o \
	$(BUILD_DIR)/src/dolphin/gx/GXLight.o \
	$(BUILD_DIR)/src/dolphin/gx/GXTexture.o \
	$(BUILD_DIR)/src/dolphin/gx/GXBump.o \
	$(BUILD_DIR)/src/dolphin/gx/GXTev.o \
	$(BUILD_DIR)/src/dolphin/gx/GXPixel.o \
	$(BUILD_DIR)/src/dolphin/gx/GXTransform.o \
	$(BUILD_DIR)/src/dolphin/gx/GXPerf.o \
	$(BUILD_DIR)/src/dolphin/pad/Padclamp.o \
	$(BUILD_DIR)/src/dolphin/pad/Pad.o \
	$(BUILD_DIR)/src/dolphin/dvd/dvdlow.o \
	$(BUILD_DIR)/src/dolphin/dvd/dvdfs.o \
	$(BUILD_DIR)/src/dolphin/dvd/dvd.o \
	$(BUILD_DIR)/src/dolphin/dvd/dvdqueue.o \
	$(BUILD_DIR)/src/dolphin/dvd/dvderror.o \
	$(BUILD_DIR)/src/dolphin/dvd/dvdidutils.o \
	$(BUILD_DIR)/src/dolphin/dvd/dvdFatal.o \
	$(BUILD_DIR)/src/dolphin/dvd/fstload.o \
	$(BUILD_DIR)/src/dolphin/demo/DEMOInit.o \
	$(BUILD_DIR)/src/dolphin/demo/DEMOPuts.o \
	$(BUILD_DIR)/src/dolphin/demo/DEMOFont.o \
	$(BUILD_DIR)/src/dolphin/demo/DEMOPad.o \
	$(BUILD_DIR)/src/dolphin/demo/DEMOStats.o \
	$(BUILD_DIR)/src/dolphin/ai/ai.o \
	$(BUILD_DIR)/src/dolphin/ar/ar.o \
	$(BUILD_DIR)/src/dolphin/dsp/dsp.o \
	$(BUILD_DIR)/src/dolphin/dsp/dsp_debug.o \
	$(BUILD_DIR)/src/dolphin/dsp/dsp_task.o \
	$(BUILD_DIR)/src/dolphin/card/CARDBios.o \
	$(BUILD_DIR)/src/dolphin/card/CARDUnlock.o \
	$(BUILD_DIR)/src/dolphin/card/CARDRdwr.o \
	$(BUILD_DIR)/src/dolphin/card/CARDBlock.o \
	$(BUILD_DIR)/src/dolphin/card/CARDDir.o \
	$(BUILD_DIR)/src/dolphin/card/CARDCheck.o \
	$(BUILD_DIR)/src/dolphin/card/CARDMount.o \
	$(BUILD_DIR)/src/dolphin/card/CARDFormat.o \
	$(BUILD_DIR)/src/dolphin/card/CARDOpen.o \
	$(BUILD_DIR)/src/dolphin/card/CARDCreate.o \
	$(BUILD_DIR)/src/dolphin/card/CARDRead.o \
	$(BUILD_DIR)/src/dolphin/card/CARDWrite.o \
	$(BUILD_DIR)/src/dolphin/card/CARDDelete.o \
	$(BUILD_DIR)/src/dolphin/card/CARDStat.o \
	$(BUILD_DIR)/src/dolphin/card/CARDNet.o \
	$(BUILD_DIR)/src/dolphin/thp/THPDec.o \
	$(BUILD_DIR)/src/dolphin/thp/THPAudio.o \
	$(BUILD_DIR)/src/dolphin/tex/texPalette.o \
	$(BUILD_DIR)/src/metrotrk/mainloop.o \
	$(BUILD_DIR)/src/metrotrk/nubevent.o \
	$(BUILD_DIR)/src/metrotrk/nubinit.o \
	$(BUILD_DIR)/src/metrotrk/msg.o \
	$(BUILD_DIR)/src/metrotrk/msgbuf.o \
	$(BUILD_DIR)/src/metrotrk/serpoll.o \
	$(BUILD_DIR)/src/metrotrk/usr_put.o \
	$(BUILD_DIR)/src/metrotrk/dispatch.o \
	$(BUILD_DIR)/src/metrotrk/msghndlr.o \
	$(BUILD_DIR)/src/metrotrk/support.o \
	$(BUILD_DIR)/src/metrotrk/mutex_TRK.o \
	$(BUILD_DIR)/src/metrotrk/notify.o \
	$(BUILD_DIR)/src/metrotrk/flush_cache.o \
	$(BUILD_DIR)/src/metrotrk/mem_TRK.o \
	$(BUILD_DIR)/src/metrotrk/__exception.o \
	$(BUILD_DIR)/src/metrotrk/targimpl.o \
	$(BUILD_DIR)/src/metrotrk/dolphin_trk.o \
	$(BUILD_DIR)/src/metrotrk/mpc_7xx_603e.o \
	$(BUILD_DIR)/src/metrotrk/main_TRK.o \
	$(BUILD_DIR)/src/metrotrk/dolphin_trk_glue.o \
	$(BUILD_DIR)/src/metrotrk/targcont.o \
	$(BUILD_DIR)/src/runtime/__mem.o \
	$(BUILD_DIR)/src/runtime/__va_arg.o \
	$(BUILD_DIR)/src/runtime/global_destructor_chain.o \
	$(BUILD_DIR)/src/runtime/runtime.o \
	$(BUILD_DIR)/src/libc/abort_exit.o \
	$(BUILD_DIR)/src/libc/ansi_files.o \
	$(BUILD_DIR)/src/libc/ansi_fp.o \
	$(BUILD_DIR)/src/libc/buffer_io.o \
	$(BUILD_DIR)/src/libc/critical_regions.ppc_eabi.o \
	$(BUILD_DIR)/src/libc/ctype.o \
	$(BUILD_DIR)/src/libc/direct_io.o \
	$(BUILD_DIR)/src/libc/errno.o \
	$(BUILD_DIR)/src/libc/mbstring.o \
	$(BUILD_DIR)/src/libc/mem.o \
	$(BUILD_DIR)/src/libc/mem_funcs.o \
	$(BUILD_DIR)/src/libc/misc_io.o \
	$(BUILD_DIR)/src/libc/printf.o \
	$(BUILD_DIR)/src/libc/scanf.o \
	$(BUILD_DIR)/src/libc/string.o \
	$(BUILD_DIR)/src/libc/strtoul.o \
	$(BUILD_DIR)/src/libc/uart_console_io.o \
	$(BUILD_DIR)/src/libc/float.o \
	$(BUILD_DIR)/src/libc/wchar_io.o \
	$(BUILD_DIR)/src/libc/e_asin.o \
	$(BUILD_DIR)/src/libc/e_pow.o \
	$(BUILD_DIR)/src/libc/fminmaxdim.o \
	$(BUILD_DIR)/src/libc/s_ceil.o \
	$(BUILD_DIR)/src/libc/s_copysign.o \
	$(BUILD_DIR)/src/libc/s_floor.o \
	$(BUILD_DIR)/src/libc/s_frexp.o \
	$(BUILD_DIR)/src/libc/s_ldexp.o \
	$(BUILD_DIR)/src/libc/w_pow.o \
	$(BUILD_DIR)/src/libc/hyperbolicsf.o \
	$(BUILD_DIR)/src/libc/log10f.o \
	$(BUILD_DIR)/src/libc/trigf.o \
	$(BUILD_DIR)/src/libc/math_inlines.o \
	$(BUILD_DIR)/src/libc/common_float_tables.o \
	$(BUILD_DIR)/src/debugger/AmcExi2Stubs.o \
	$(BUILD_DIR)/src/debugger/DebuggerDriver.o \
	$(BUILD_DIR)/src/debugger/odenotstub.o \
